---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-contrib-telemetrygen
  namespace: opentelemetry-demo
  labels:
    opentelemetry.io/name: collector-contrib-telemetrygen
    app.kubernetes.io/instance: telemetrygen
    app.kubernetes.io/component: collector-contrib
    app.kubernetes.io/name: collector-contrib-telemetrygen
    app.kubernetes.io/version: "0.127.0"
    app.kubernetes.io/part-of: collector-contrib-telemetrygen
spec:
  replicas: 20
  selector:
    matchLabels:
      opentelemetry.io/name: collector-contrib-telemetrygen
  template:
    metadata:
      labels:
        opentelemetry.io/name: collector-contrib-telemetrygen
        app.kubernetes.io/instance: telemetrygen
        app.kubernetes.io/component: collector-contrib
    spec:
      containers:
        - name: traces
          image: 'ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.127.0'
          args: ["traces", "--otlp-insecure", "--rate=100", "--duration=60m", "--otlp-endpoint=$(OTEL_EXPORTER_OTLP_TRACES_ENDPOINT)"]
          imagePullPolicy: IfNotPresent
          env:
          - name: OTEL_SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels['app.kubernetes.io/component']
          - name: OTEL_COLLECTOR_NAME
            value: 'opentelemetry-collector-bom'
          - name: OTEL_COLLECTOR_NAMESPACE
            value: 'opentelemetry'
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: $(OTEL_COLLECTOR_NAME).$(OTEL_COLLECTOR_NAMESPACE).svc.cluster.local:4317
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
        - name: metrics
          image: 'ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.127.0'
          args: ["metrics", "--otlp-insecure", "--rate=100", "--duration=60m", "--otlp-endpoint=$(OTEL_EXPORTER_OTLP_METRICS_ENDPOINT)"]
          imagePullPolicy: IfNotPresent
          env:
          - name: OTEL_SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels['app.kubernetes.io/component']
          - name: OTEL_COLLECTOR_NAME
            value: 'opentelemetry-collector-bom'
          - name: OTEL_COLLECTOR_NAMESPACE
            value: 'opentelemetry'
          - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
            value: $(OTEL_COLLECTOR_NAME).$(OTEL_COLLECTOR_NAMESPACE).svc.cluster.local:4317
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
        - name: logs
          image: 'ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.127.0'
          args: ["logs", "--otlp-insecure", "--rate=100", "--duration=60m", "--otlp-endpoint=$(OTEL_EXPORTER_OTLP_LOGS_ENDPOINT)"]
          imagePullPolicy: IfNotPresent
          env:
          - name: OTEL_SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels['app.kubernetes.io/component']
          - name: OTEL_COLLECTOR_NAME
            value: 'opentelemetry-collector-bom'
          - name: OTEL_COLLECTOR_NAMESPACE
            value: 'opentelemetry'
          - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
            value: $(OTEL_COLLECTOR_NAME).$(OTEL_COLLECTOR_NAMESPACE).svc.cluster.local:4317
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
---