services:
  # Used by Redis storage extension
  otel-valkey:
    container_name: otel-valkey
    image: docker.io/valkey/valkey:8.1.1-alpine3.21
    restart: always
    ports:
      - "6379:6379"
    command: ["valkey-server", "/etc/valkey/valkey.conf"]
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./configs/valkey.conf:/etc/valkey/valkey.conf:ro
      - ./valkey:/data

  # Receives requests from otel-gen and forwards to otel-two
  otel-one:
    container_name: otel-one
    image: docker.io/otel/opentelemetry-collector-contrib:0.126.0
    restart: always
    volumes:
      - ./configs/otel-one.yaml:/etc/otel/config.yaml:ro
    command: ["--config", "/etc/otel/config.yaml"]
    depends_on:
      otel-valkey:
        condition: service_healthy

  # Receives signals from otel-one and sends to stdout via debug exporter
  otel-two:
    container_name: otel-two
    image: docker.io/otel/opentelemetry-collector-contrib:0.126.0
    restart: always
    volumes:
      - ./configs/otel-two.yaml:/etc/otel/config.yaml:ro
    command: ["--config", "/etc/otel/config.yaml"]
    depends_on:
      otel-valkey:
        condition: service_healthy

  # Generate traces and send to otel-one
  otel-gen-traces:
    container_name: otel-gen-traces
    image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.126.0
    restart: always
    command: traces --otlp-insecure --otlp-endpoint otel-one:4317 --duration 60s --rate 1
    depends_on:
      otel-one:
        condition: service_started

  # Generate metrics and send to otel-one
  otel-gen-metrics:
    container_name: otel-gen-metrics
    image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.126.0
    restart: always
    command: metrics --otlp-insecure --otlp-endpoint otel-one:4317 --duration 60s --rate 1
    depends_on:
      otel-one:
        condition: service_started

  # Generate logs and send to otel-one
  otel-gen-logs:
    container_name: otel-gen-logs
    image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.126.0
    restart: always
    command: logs --otlp-insecure --otlp-endpoint otel-one:4317 --duration 60s --rate 1
    depends_on:
      otel-one:
        condition: service_started