---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: collector-config
  namespace: opentelemetry
data:
  collector.yaml: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:4317
            http:
              endpoint: ${env:MY_POD_IP}:4318

      # Processors
      processors:
        batch:
          send_batch_size: 200 # 8192
          timeout: 1s
        memory_limiter:
          check_interval: 5s
          limit_percentage: 80
          spike_limit_percentage: 25

      # Exporters
      exporters:
        debug:
          verbosity: detailed
          sampling_initial: 5
          sampling_thereafter: 200
        otlp:
          # endpoint: "opentelemetry-collector.opentelemetry.svc.cluster.local:4317"
          endpoint: "0.0.0.0:4317"
          compression: zstd
          tls:
            insecure: true

      # Extensions
      extensions:
        health_check:
          endpoint: "0.0.0.0:13133"
          path: "/"

      # Service
      service:
        telemetry:
          logs:
            level: DEBUG
        extensions:
          - health_check
        pipelines:
          logs:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - otlp
              - debug
          metrics:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - otlp
              - debug
          traces:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - otlp
              - debug
---