---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: collector-config
  namespace: opentelemetry
data:
  collector.yaml: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:4317
            http:
              endpoint: ${env:MY_POD_IP}:4318

      # Processors
      processors:
        batch:
          send_batch_size: 200 # 8192
          timeout: 1s
        memory_limiter:
          check_interval: 5s
          limit_percentage: 80
          spike_limit_percentage: 25

      # Exporters
      exporters:
        debug:
          verbosity: detailed
          sampling_initial: 5
          sampling_thereafter: 200
        otlp:
          endpoint: "otel-tui.opentelemetry.svc.cluster.local:4317"
          compression: zstd
          tls:
            insecure: true
          sending_queue:
            storage: file_storage
            enabled: true
            num_consumers: 10
            wait_for_result: false
            block_on_overflow: false
            sizer: requests
            queue_size: 1000
          timeout: 5s
          retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_interval: 30s
            max_elapsed_time: 600s
            multiplier: 1.5
        otlphttp:
          endpoint: "http://otel-tui.opentelemetry.svc.cluster.local:4318"
          compression: zstd
          encoding: proto
          tls:
            insecure: false
          sending_queue:
            storage: file_storage
            enabled: true
            num_consumers: 10
            wait_for_result: false
            block_on_overflow: false
            sizer: requests
            queue_size: 1000
          timeout: 5s
          retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_interval: 30s
            max_elapsed_time: 600s
            multiplier: 1.5

      # Extensions
      extensions:
        health_check:
          endpoint: "0.0.0.0:13133"
          path: "/"
        file_storage:
          directory: /var/lib/otelcol/storage
          create_directory: true
          timeout: 1s
          compaction:
            on_start: true
            directory: /var/lib/otelcol/compaction
            max_transaction_size: 65_536
            rebound_needed_threshold_mib: 10
            rebound_trigger_threshold_mib: 1
            check_interval: 5s
          fsync: false

      # Service
      service:
        telemetry:
          logs:
            level: DEBUG
        extensions:
          - health_check
          - file_storage
        pipelines:
          logs:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - otlp
          metrics:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - otlp
          traces:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - otlp
---