apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 0_namespace.yaml
  - 1_configmap_otel_config.yaml
  - 1_configmap_otel_wrapper.yaml
  - 2_rbac.yaml
  - 3_service.yaml
  - 4_deployment.yaml
  - 5_hpa.yaml